#Clase 1
spring.application.name=tienda
#Para definir el puerto donde "escuchará" el servidor
server.port=8080

#Clase 2
#Para definir el formato de despliegue de fecha/hora del log en la consola
logging.pattern.dateformart=hh:mm

#Para eliminar mensajes invasivos de Sprint
sprint.main.banner-mode=off

#En desarrollo el "cache" del servidor (false), en produccion "true"
sprint.thymeleaf.cache=false